// src/app/core/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';

import { SettingsService } from '../../shared/services/settings.service';
import { Settings } from '../../shared/models/settings';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss']
})
export class SettingsComponent implements OnInit {
  settings: Settings;

  constructor(private _settingsService: SettingsService) {
    this.settings = this._settingsService.settings;
  }

  ngOnInit() {
  }

  closeSettings() {
    this._settingsService.toggleSettings();
  }

  toggleOpenLinksInNewTab() {
    this._settingsService.toggleOpenLinksInNewTab();
  }

  selectTheme(theme) {
    this._settingsService.setTheme(theme);
  }

  selectAuto() {
    this._settingsService.enableAutoTheme();
  }

  changeTitleFont(val){
    this._settingsService.setFont(val);
  }

  changeSpacing(val){
    this._settingsService.setSpacing(val);
  }
}

<div id="popup1" class="overlay">
    <div class="popup">
        <h1>Settings</h1>
        <hr>
        <span class="close" (click)="closeSettings()">&times;</span>
        <div class="content">
            <div class="control-section">
                <h2>Links</h2>
                <input 
                    type="checkbox" 
                    [checked]="settings.openLinkInNewTab" 
                    (change)="toggleOpenLinksInNewTab()" />
                    Open links in a new tab
            </div>
            <div class="theme-controls">
                <div class="control-section">
                    <h2>Select a theme</h2>
                    <div>
                        <label>
                        <input #auto 
                            name="theme" 
                            type="radio" 
                            value="auto" 
                            [checked]="settings.autoTheme"
                            (click)="selectAuto()" />
                            Auto (follow system)
                        </label>
                    </div>
                    <div>
                        <label>
                        <input #default 
                            name="theme" 
                            type="radio" 
                            value="default" 
                            [checked]="!settings.autoTheme && settings.theme === default.value"
                            (click)="selectTheme(default.value)" />
                            Default
                        </label>
                    </div>
                    <div>
                        <label>
                        <input #night 
                            name="theme" 
                            type="radio" 
                            value="night" 
                            [checked]="!settings.autoTheme && settings.theme === night.value" 
                            (click)="selectTheme(night.value)" />
                            Night
                        </label>
                    </div>
                    <div>
                        <label>
                        <input 
                            #amoledblack 
                            name="theme" 
                            type="radio" 
                            value="amoledblack" 
                            [checked]="!settings.autoTheme && settings.theme === amoledblack.value"
                            (click)="selectTheme(amoledblack.value)" />
                            Black (AMOLED)
                        </label>
                    </div>
                </div>
                <div class="control-section">
                    <h2>Change Font</h2>
                    <div>
                        <label>
                        Font size:
                        <input 
                            #titleFont 
                            min="1" 
                            [value]="settings.titleFontSize" 
                            name="theme" 
                            type="number" 
                            (keyup)="changeTitleFont(titleFont.value)" />
                        </label>
                    </div>
                    <div>
                        <label>
                        List spacing:
                        <input 
                            #listSpacing 
                            min="0" 
                            [value]="settings.listSpacing" 
                            name="theme" 
                            type="number" 
                            (keyup)="changeSpacing(listSpacing.value)" />
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// react-app/src/core/settings/SettingsComponent.tsx
import { scope } from '../../shared/scope';
import { settingsService } from '../../shared/services/settings-service';
import { useSettings } from '../../shared/services/use-settings';
import './settings.component.scss';

const ng = scope('settings');

export function SettingsComponent() {
    const settings = useSettings();
    return (
        <app-settings {...ng}>
            <div {...ng} id="popup1" className="overlay">
                <div {...ng} className="popup">
                    <h1 {...ng}>Settings</h1>
                    <hr {...ng} />
                    <span {...ng} className="close" onClick={() => settingsService.toggleSettings()}>
                        &times;
                    </span>
                    <div {...ng} className="content">
                        <div {...ng} className="control-section">
                            <h2 {...ng}>Links</h2>
                            <input
                                {...ng}
                                type="checkbox"
                                checked={settings.openLinkInNewTab}
                                onChange={() => settingsService.toggleOpenLinksInNewTab()}
                            />
                            {' Open links in a new tab '}
                        </div>
                        <div {...ng} className="theme-controls">
                            <div {...ng} className="control-section">
                                <h2 {...ng}>Select a theme</h2>
                                <div {...ng}>
                                    <label {...ng}>
                                        <input
                                            {...ng}
                                            name="theme"
                                            type="radio"
                                            value="default"
                                            checked={settings.theme === 'default'}
                                            onChange={() => settingsService.setTheme('default')}
                                        />
                                        {' Default '}
                                    </label>
                                </div>
                                <div {...ng}>
                                    <label {...ng}>
                                        <input
                                            {...ng}
                                            name="theme"
                                            type="radio"
                                            value="night"
                                            checked={settings.theme === 'night'}
                                            onChange={() => settingsService.setTheme('night')}
                                        />
                                        {' Night '}
                                    </label>
                                </div>
                                <div {...ng}>
                                    <label {...ng}>
                                        <input
                                            {...ng}
                                            name="theme"
                                            type="radio"
                                            value="amoledblack"
                                            checked={settings.theme === 'amoledblack'}
                                            onChange={() => settingsService.setTheme('amoledblack')}
                                        />
                                        {' Black (AMOLED) '}
                                    </label>
                                </div>
                            </div>
                            <div {...ng} className="control-section">
                                <h2 {...ng}>Change Font</h2>
                                <div {...ng}>
                                    <label {...ng}>
                                        {' Font size: '}
                                        <input
                                            {...ng}
                                            min="1"
                                            defaultValue={settings.titleFontSize}
                                            name="theme"
                                            type="number"
                                            onKeyUp={(event) => settingsService.setFont(event.currentTarget.value)}
                                        />
                                    </label>
                                </div>
                                <div {...ng}>
                                    <label {...ng}>
                                        {' List spacing: '}
                                        <input
                                            {...ng}
                                            min="0"
                                            defaultValue={settings.listSpacing}
                                            name="theme"
                                            type="number"
                                            onKeyUp={(event) => settingsService.setSpacing(event.currentTarget.value)}
                                        />
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </app-settings>
    );
}
