// src/app/feeds/item/item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Story } from '../../shared/models/story';

import { SettingsService } from '../../shared/services/settings.service';
import { BookmarkService } from '../../shared/services/bookmark.service';
import { Settings } from '../../shared/models/settings';

@Component({
  selector: 'item',
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.scss']
})
export class ItemComponent implements OnInit {
  @Input() item: Story;
  settings: Settings;
  isBookmarked: boolean;

  constructor(
    private _settingsService: SettingsService,
    private _bookmarkService: BookmarkService
  ) {
    this.settings = this._settingsService.settings;
  }

  ngOnInit() {
    this.isBookmarked = this._bookmarkService.isBookmarked(this.item.id);
  }

  toggleBookmark(): void {
    this.isBookmarked = this._bookmarkService.toggleBookmark(this.item);
  }

  get hasUrl(): boolean {
    return this.item.url.indexOf('http') === 0;
  }
}

<div [ngStyle]="{'margin-bottom': settings.listSpacing+'px'}">
  <p *ngIf="hasUrl">
    <a class="title" [ngStyle]="{'font-size': settings.titleFontSize+'px'}" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
      {{item.title}}
    </a>
    <span *ngIf="item.domain" class="domain">({{item.domain}})</span>
  </p>
  <p *ngIf="!hasUrl">
    <a class="title" [ngStyle]="{'font-size': settings.titleFontSize+'px'}" [routerLink]="['/item', item.id]" routerLinkActive="active">
      {{item.title}}
    </a>
  </p>
  <div class="subtext-palm">
    <div class="details" *ngIf="item.type !== 'job'">
      <span class="name"><a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a></span>
      <span class="right">
        {{item.points}} ★
        <span class="bookmark-icon" (click)="toggleBookmark()" [class.bookmarked]="isBookmarked" title="{{isBookmarked ? 'Remove bookmark' : 'Save story'}}">
          &#9733;
        </span>
      </span>
    </div>
    <div class="details">
    {{ item.time_ago }}
    <a [routerLink]="['/item', item.id]" routerLinkActive="active" class="comment-number" *ngIf="item.type !== 'job'"> •
      {{item.comments_count | comment }}
    </a>
    </div>
  </div>
  <div class="subtext-laptop">
    <span *ngIf="item.type !== 'job'">
      {{item.points}} points by
      <a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a>
    </span>
    <span [class.item-details]="item.type !== 'job'">
      {{ item.time_ago }}
      <span *ngIf="item.type !== 'job'"> |
        <a [routerLink]="['/item', item.id]" routerLinkActive="active">
          {{item.comments_count | comment }}
        </a>
      </span>
    </span>
    <span class="bookmark-icon" (click)="toggleBookmark()" [class.bookmarked]="isBookmarked" title="{{isBookmarked ? 'Remove bookmark' : 'Save story'}}">
      &#9733;
    </span>
  </div>
</div>

// web-react/src/components/Item.tsx
import { Link } from 'react-router-dom';
import type { Story } from '../models';
import { useSettingsStore } from '../stores/settings';
import { commentLabel } from '../utils/comment-label';
import './Item.scss';

export function Item({ item }: { item: Story }) {
  const openLinkInNewTab = useSettingsStore((s) => s.openLinkInNewTab);
  const titleFontSize = useSettingsStore((s) => s.titleFontSize);
  const listSpacing = useSettingsStore((s) => s.listSpacing);

  const hasUrl = item.url != null && item.url.indexOf('http') === 0;
  const titleStyle = { fontSize: `${titleFontSize}px` };

  return (
    <div className="item-block" style={{ marginBottom: `${listSpacing}px` }}>
      {hasUrl ? (
        <p>
          <a
            className="title"
            style={titleStyle}
            href={item.url}
            target={openLinkInNewTab ? '_blank' : undefined}
            rel={openLinkInNewTab ? 'noopener' : undefined}
          >
            {item.title}
          </a>
          {item.domain && <span className="domain">({item.domain})</span>}
        </p>
      ) : (
        <p>
          <Link className="title" style={titleStyle} to={`/item/${item.id}`}>
            {item.title}
          </Link>
        </p>
      )}
      <div className="subtext-palm">
        {item.type !== 'job' && (
          <div className="details">
            <span className="name">
              <Link to={`/user/${item.user}`}>{item.user}</Link>
            </span>
            <span className="right">{item.points} ★</span>
          </div>
        )}
        <div className="details">
          {item.time_ago}
          {item.type !== 'job' && (
            <Link to={`/item/${item.id}`} className="comment-number">
              {' '}• {commentLabel(item.comments_count)}
            </Link>
          )}
        </div>
      </div>
      <div className="subtext-laptop">
        {item.type !== 'job' && (
          <span>
            {item.points} points by <Link to={`/user/${item.user}`}>{item.user}</Link>
          </span>
        )}
        <span className={item.type !== 'job' ? 'item-details' : undefined}>
          {item.time_ago}
          {item.type !== 'job' && (
            <span>
              {' '}| <Link to={`/item/${item.id}`}>{commentLabel(item.comments_count)}</Link>
            </span>
          )}
        </span>
      </div>
    </div>
  );
}
