// src/app/feeds/feed/feed.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { Subscription } from 'rxjs';
import { ActivatedRoute } from '@angular/router';

import { HackerNewsAPIService } from '../../shared/services/hackernews-api.service';
import { Story } from '../../shared/models/story';

@Component({
  selector: 'app-feed',
  templateUrl: './feed.component.html',
  styleUrls: ['./feed.component.scss']
})

export class FeedComponent implements OnInit {
  typeSub: Subscription;
  pageSub: Subscription;
  items: Story[];
  feedType: string;
  pageNum: number;
  listStart: number;
  authorFilter = '';
  errorMessage = '';

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private route: ActivatedRoute
  ) { }

  get visibleItems(): Story[] {
    const author = this.authorFilter.trim().toLowerCase();

    if (!author || !this.items) {
      return this.items;
    }

    return this.items.filter(item => item.user && item.user.toLowerCase().indexOf(author) !== -1);
  }

  get showAuthorFilter(): boolean {
    return this.feedType !== 'jobs' && !!this.items && this.items.length > 0;
  }

  get listMargin(): boolean {
    return this.feedType !== 'jobs' && !this.showAuthorFilter;
  }

  clearAuthorFilter() {
    this.authorFilter = '';
  }

  ngOnInit() {
    this.typeSub = this.route
      .data
      .subscribe(data => {
        this.feedType = (data as any).feedType;
      });

    this.pageSub = this.route.params.subscribe(params => {
      this.pageNum = params['page'] ? +params['page'] : 1;
      this._hackerNewsAPIService.fetchFeed(this.feedType, this.pageNum)
        .subscribe(
          items => this.items = items,
          error => this.errorMessage = 'Could not load ' + this.feedType + ' stories.',
          () => {
            this.listStart = ((this.pageNum - 1) * 30) + 1;
            window.scrollTo(0, 0);
          }
        );
    });
  }
}

<div class="main-content">
  <app-loader *ngIf="!items && !errorMessage"></app-loader>
  <app-error-message [message]="errorMessage" *ngIf="!items && errorMessage !==''"></app-error-message>

  <div *ngIf="items">
    <p class="job-header" *ngIf="feedType === 'jobs'">
      These are jobs at startups that were funded by Y Combinator.
      You can also get a job at a YC startup through <a href="https://triplebyte.com/?ref=yc_jobs">Triplebyte</a>.
    </p>
    <div class="author-filter" *ngIf="showAuthorFilter">
      <input type="text" name="authorFilter" placeholder="Filter by author" aria-label="Filter by author"
        [(ngModel)]="authorFilter">
      <a class="clear" *ngIf="authorFilter" (click)="clearAuthorFilter()">Clear</a>
    </div>
    <app-story-list *ngIf="feedType !== 'new'" [items]="visibleItems" [listStart]="listStart"
      [listMargin]="listMargin"></app-story-list>
    <p class="no-matches" *ngIf="visibleItems.length === 0 && authorFilter">
      No stories by an author matching “{{ authorFilter }}” on this page.
    </p>
    <div class="nav">
      <a *ngIf="listStart !== 1" [routerLink]="['/' + feedType, pageNum - 1]" routerLinkActive="active" class="prev">
        ‹ Prev
      </a>
      <a *ngIf="items.length === 30" [routerLink]="['/' + feedType, pageNum + 1]" routerLinkActive="active" class="more">
        More ›
      </a>
    </div>
  </div>
</div>

// react-app/src/components/Feed/Feed.tsx
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';

import { fetchFeed } from '../../api/hackerNews';
import type { Story } from '../../models/story';
import { ErrorMessage } from '../ErrorMessage/ErrorMessage';
import { Item } from '../Item/Item';
import { Loader } from '../Loader/Loader';

import './Feed.scss';

export function Feed({ feedType }: { feedType: string }) {
    const params = useParams();
    const pageNum = params.page ? +params.page : 1;

    const [items, setItems] = useState<Story[] | undefined>(undefined);
    const [errorMessage, setErrorMessage] = useState('');
    const [listStart, setListStart] = useState<number | undefined>(undefined);

    useEffect(() => {
        const controller = new AbortController();

        fetchFeed(feedType, pageNum, controller.signal)
            .then((fetchedItems) => {
                setItems(fetchedItems);
                setListStart((pageNum - 1) * 30 + 1);
                window.scrollTo(0, 0);
            })
            .catch((error: unknown) => {
                if (error instanceof DOMException && error.name === 'AbortError') {
                    return;
                }
                setErrorMessage('Could not load ' + feedType + ' stories.');
            });

        return () => controller.abort();
    }, [feedType, pageNum]);

    return (
        <div className="c-feed">
            <div className="main-content">
                {!items && !errorMessage ? <Loader /> : null}
                {!items && errorMessage !== '' ? <ErrorMessage message={errorMessage} /> : null}

                {items ? (
                    <div>
                        {feedType === 'jobs' ? (
                            <p className="job-header">
                                These are jobs at startups that were funded by Y Combinator. You can also get a job at a
                                YC startup through <a href="https://triplebyte.com/?ref=yc_jobs">Triplebyte</a>
                                {'. '}
                            </p>
                        ) : null}
                        <ol className={feedType !== 'jobs' ? 'list-margin' : undefined} start={listStart}>
                            {items.map((item) => (
                                <li key={item.id} className="post">
                                    <Item item={item} />
                                </li>
                            ))}
                        </ol>
                        <div className="nav">
                            {listStart !== 1 ? (
                                <Link to={`/${feedType}/${pageNum - 1}`} className="prev">
                                    {' ‹ Prev '}
                                </Link>
                            ) : null}
                            {items.length === 30 ? (
                                <Link to={`/${feedType}/${pageNum + 1}`} className="more">
                                    {' More › '}
                                </Link>
                            ) : null}
                        </div>
                    </div>
                ) : null}
            </div>
        </div>
    );
}
