// src/app/user/user.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs/Subscription';

import { HackerNewsAPIService } from '../shared/services/hackernews-api.service';
import { User } from '../shared/models/user';

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.scss']
})
export class UserComponent implements OnInit {
  sub: Subscription;
  user: User;
  errorMessage = '';

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private route: ActivatedRoute,
    private _location: Location
  ) {}

  ngOnInit() {
    this.sub = this.route.params.subscribe(params => {
      const userID = params.id;
      this._hackerNewsAPIService.fetchUser(userID).subscribe(data => {
        this.user = data;
      }, error => this.errorMessage = 'Could not load user ' + userID + '.');
    });
  }

  goBack() {
    this._location.back();
  }
}

<app-loader *ngIf="!user && !errorMessage"></app-loader>
<app-error-message [message]="errorMessage" *ngIf="!user && errorMessage !== ''"></app-error-message>

<div *ngIf="user" class="profile">
  <div class="mobile item-header">
    <p class="title-block">
      <span class="back-button" (click)="goBack()"></span>
      Profile: {{ user.id }}
    </p>
  </div>
  <div class="main-details">
    <span class="name">{{ user.id }}</span>
    <span class="right">{{ user.karma }} ★</span>
    <p class="age">Created {{ user.created }}</p>
  </div>
  <div class="other-details" *ngIf="user.about">
    <p [innerHTML]="user.about | safeHtml"></p>
  </div>
</div>

// react-app/src/components/User/User.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import { fetchUser } from '../../api/hackerNews';
import type { User as UserModel } from '../../models/user';
import { sanitizeHtml } from '../../utils/sanitizeHtml';
import { ErrorMessage } from '../ErrorMessage/ErrorMessage';
import { Loader } from '../Loader/Loader';

import './User.scss';

export default function User() {
    const params = useParams();
    const navigate = useNavigate();
    const userID = params.id as string;

    const [user, setUser] = useState<UserModel | undefined>(undefined);
    const [errorMessage, setErrorMessage] = useState('');

    useEffect(() => {
        const controller = new AbortController();

        fetchUser(userID, controller.signal)
            .then((data) => setUser(data))
            .catch((error: unknown) => {
                if (error instanceof DOMException && error.name === 'AbortError') {
                    return;
                }
                setErrorMessage('Could not load user ' + userID + '.');
            });

        return () => controller.abort();
    }, [userID]);

    return (
        <div className="c-user">
            {!user && !errorMessage ? <Loader /> : null}
            {!user && errorMessage !== '' ? <ErrorMessage message={errorMessage} /> : null}

            {user ? (
                <div className="profile">
                    <div className="mobile item-header">
                        <p className="title-block">
                            <span className="back-button" onClick={() => navigate(-1)}></span>
                            {` Profile: ${user.id} `}
                        </p>
                    </div>
                    <div className="main-details">
                        <span className="name">{user.id}</span>
                        <span className="right">{`${user.karma} ★`}</span>
                        <p className="age">{`Created ${user.created}`}</p>
                    </div>
                    {user.about ? (
                        <div className="other-details">
                            <p dangerouslySetInnerHTML={{ __html: sanitizeHtml(user.about) }}></p>
                        </div>
                    ) : null}
                </div>
            ) : null}
        </div>
    );
}
