// react-app/src/user/UserComponent.tsx
import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router';

import { fetchUser } from '../shared/api/hackernews-api';
import { ErrorMessageComponent } from '../shared/components/error-message/ErrorMessageComponent';
import { LoaderComponent } from '../shared/components/loader/LoaderComponent';
import type { User } from '../shared/models/user';
import { scope } from '../shared/scope';
import './user.component.scss';

const ng = scope('user');

export function UserComponent() {
    const { id } = useParams();
    const userID = id ?? '';
    const navigate = useNavigate();
    const [user, setUser] = useState<User | undefined>(undefined);
    const [errorMessage, setErrorMessage] = useState('');
    const latestRequest = useRef(0);

    useEffect(() => {
        const controller = new AbortController();
        const request = ++latestRequest.current;
        fetchUser(userID, controller.signal).then(
            (fetched) => {
                if (request === latestRequest.current) {
                    setUser(fetched);
                }
            },
            () => {
                if (request === latestRequest.current) {
                    setErrorMessage(`Could not load user ${userID}.`);
                }
            }
        );
        return () => controller.abort();
    }, [userID]);

    return (
        <app-user>
            {!user && errorMessage === '' ? <LoaderComponent /> : null}
            {!user && errorMessage !== '' ? <ErrorMessageComponent message={errorMessage} /> : null}

            {user ? (
                <div {...ng} className="profile">
                    <div {...ng} className="mobile item-header">
                        <p {...ng} className="title-block">
                            <span {...ng} className="back-button" onClick={() => navigate(-1)}></span>
                            {` Profile: ${user.id} `}
                        </p>
                    </div>
                    <div {...ng} className="main-details">
                        <span {...ng} className="name">
                            {user.id}
                        </span>
                        <span {...ng} className="right">
                            {`${user.karma} \u2605`}
                        </span>
                        <p {...ng} className="age">
                            {`Created ${user.created}`}
                        </p>
                    </div>
                    {user.about ? (
                        <div {...ng} className="other-details">
                            <p {...ng} dangerouslySetInnerHTML={{ __html: user.about }}></p>
                        </div>
                    ) : null}
                </div>
            ) : null}
        </app-user>
    );
}

// src/app/user/user.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs/Subscription';

import { HackerNewsAPIService } from '../shared/services/hackernews-api.service';
import { User } from '../shared/models/user';

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.scss']
})
export class UserComponent implements OnInit {
  sub: Subscription;
  user: User;
  errorMessage = '';

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private route: ActivatedRoute,
    private _location: Location
  ) {}

  ngOnInit() {
    this.sub = this.route.params.subscribe(params => {
      const userID = params.id;
      this._hackerNewsAPIService.fetchUser(userID).subscribe(data => {
        this.user = data;
      }, error => this.errorMessage = 'Could not load user ' + userID + '.');
    });
  }

  goBack() {
    this._location.back();
  }
}

<app-loader *ngIf="!user && !errorMessage"></app-loader>
<app-error-message [message]="errorMessage" *ngIf="!user && errorMessage !== ''"></app-error-message>

<div *ngIf="user" class="profile">
  <div class="mobile item-header">
    <p class="title-block">
      <span class="back-button" (click)="goBack()"></span>
      Profile: {{ user.id }}
    </p>
  </div>
  <div class="main-details">
    <span class="name">{{ user.id }}</span>
    <span class="right">{{ user.karma }} ★</span>
    <p class="age">Created {{ user.created }}</p>
  </div>
  <div class="other-details" *ngIf="user.about">
    <p [innerHTML]="user.about | safeHtml"></p>
  </div>
</div>
