// react-app/src/item-details/ItemDetailsComponent.tsx
import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router';

import { fetchItemContent } from '../shared/api/hackernews-api';
import { ErrorMessageComponent } from '../shared/components/error-message/ErrorMessageComponent';
import { LoaderComponent } from '../shared/components/loader/LoaderComponent';
import type { Story } from '../shared/models/story';
import { commentLabel } from '../shared/pipes/comment';
import { RouterLink } from '../shared/router/RouterLink';
import { scope } from '../shared/scope';
import { useSettings } from '../shared/services/use-settings';
import { CommentComponent } from './comment/CommentComponent';
import './item-details.component.scss';

const ng = scope('item-details');

export function ItemDetailsComponent() {
    const { id } = useParams();
    const itemID = Number(id);
    const navigate = useNavigate();
    const settings = useSettings();
    const [item, setItem] = useState<Story | undefined>(undefined);
    const [errorMessage, setErrorMessage] = useState('');
    const latestRequest = useRef(0);

    useEffect(() => {
        const controller = new AbortController();
        const request = ++latestRequest.current;
        fetchItemContent(itemID, controller.signal).then(
            (fetched) => {
                if (request === latestRequest.current) {
                    setItem(fetched);
                }
            },
            () => {
                if (request === latestRequest.current) {
                    setErrorMessage('Could not load item comments.');
                }
            }
        );
        return () => controller.abort();
    }, [itemID]);

    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    const hasUrl = item ? item.url.indexOf('http') === 0 : false;
    const target = settings.openLinkInNewTab ? '_blank' : undefined;
    const rel = settings.openLinkInNewTab ? 'noopener' : undefined;

    return (
        <app-item-details>
            <div {...ng} className="main-content">
                {!item && errorMessage === '' ? <LoaderComponent /> : null}
                {!item && errorMessage !== '' ? <ErrorMessageComponent message={errorMessage} /> : null}

                {item ? (
                    <div {...ng} className="item">
                        <div {...ng} className="mobile item-header">
                            <p {...ng} className="title-block">
                                <span {...ng} className="back-button" onClick={() => navigate(-1)}></span>
                                {hasUrl ? (
                                    <a {...ng} className="title" href={item.url} target={target} rel={rel}>
                                        {` ${item.title} `}
                                    </a>
                                ) : (
                                    <RouterLink ng={ng} className="title" to={`/item/${item.id}`}>
                                        {` ${item.title} `}
                                    </RouterLink>
                                )}
                            </p>
                        </div>
                        <div
                            {...ng}
                            className={`laptop${
                                item.comments_count > 0 || item.type === 'job' ? ' item-header' : ''
                            }`}
                        >
                            {hasUrl ? (
                                <p {...ng}>
                                    <a {...ng} className="title" href={item.url} target={target} rel={rel}>
                                        {` ${item.title} `}
                                    </a>
                                    {item.domain ? (
                                        <span {...ng} className="domain">
                                            {`(${item.domain})`}
                                        </span>
                                    ) : null}
                                </p>
                            ) : (
                                <p {...ng}>
                                    <RouterLink ng={ng} className="title" to={`/item/${item.id}`}>
                                        {` ${item.title} `}
                                    </RouterLink>
                                </p>
                            )}
                            <div {...ng} className="subtext">
                                {item.type !== 'job' ? (
                                    <span {...ng}>
                                        {` ${item.points} points by `}
                                        <RouterLink ng={ng} to={`/user/${item.user}`}>
                                            {item.user}
                                        </RouterLink>
                                    </span>
                                ) : null}
                                <span {...ng} className={item.type !== 'job' ? 'item-details' : undefined}>
                                    {` ${item.time_ago} `}
                                    {item.type !== 'job' ? (
                                        <span {...ng}>
                                            {' | '}
                                            <RouterLink ng={ng} to={`/item/${item.id}`}>
                                                {` ${commentLabel(item.comments_count)} `}
                                            </RouterLink>
                                        </span>
                                    ) : null}
                                </span>
                            </div>
                        </div>
                        {item.type === 'poll' ? (
                            <div {...ng} className="pollResults">
                                {item.poll.map((pollResult, index) => (
                                    <div {...ng} key={index} className="pollContent">
                                        <div {...ng} dangerouslySetInnerHTML={{ __html: pollResult.content }}></div>
                                        <div {...ng} className="subtext">
                                            {`${pollResult.points} points`}
                                        </div>
                                        <div
                                            {...ng}
                                            className="pollBar"
                                            style={{
                                                width: `${(pollResult.points / item.poll_votes_count) * 100}%`,
                                            }}
                                        ></div>
                                    </div>
                                ))}
                            </div>
                        ) : null}
                        <p
                            {...ng}
                            className="subject"
                            dangerouslySetInnerHTML={{ __html: item.content }}
                        ></p>
                        <ul {...ng} className="comment-list">
                            {item.comments.map((comment) => (
                                <li {...ng} key={comment.id}>
                                    <CommentComponent comment={comment} host={ng} />
                                </li>
                            ))}
                        </ul>
                    </div>
                ) : null}
            </div>
        </app-item-details>
    );
}

// src/app/item-details/item-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs/Subscription';

import { HackerNewsAPIService } from '../shared/services/hackernews-api.service';
import { SettingsService } from '../shared/services/settings.service';

import { Story } from '../shared/models/story';
import { Settings } from '../shared/models/settings';

@Component({
  selector: 'app-item-details',
  templateUrl: './item-details.component.html',
  styleUrls: ['./item-details.component.scss']
})
export class ItemDetailsComponent implements OnInit {
  sub: Subscription;
  item: Story;
  errorMessage = '';
  settings: Settings;

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private _settingsService: SettingsService,
    private route: ActivatedRoute,
    private _location: Location
  ) {
    this.settings = this._settingsService.settings;
  }

  ngOnInit() {
    this.sub = this.route.params.subscribe(params => {
      const itemID = +params.id;
      this._hackerNewsAPIService.fetchItemContent(itemID).subscribe(item => {
        this.item = item;
      }, error => this.errorMessage = 'Could not load item comments.');
    });
    window.scrollTo(0, 0);
  }

  goBack() {
    this._location.back();
  }

  get hasUrl(): boolean {
    return this.item.url.indexOf('http') === 0;
  }

}

<div class="main-content">
  <app-loader *ngIf="!item && !errorMessage"></app-loader>
  <app-error-message [message]="errorMessage" *ngIf="!item && errorMessage !== ''"></app-error-message>

  <div *ngIf="item" class="item">
    <div class="mobile item-header">
      <p class="title-block">
        <span class="back-button" (click)="goBack()"></span>
        <a *ngIf="hasUrl" class="title" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
          {{item.title}}
        </a>
        <a *ngIf="!hasUrl" class="title" [routerLink]="['/item', item.id]"
          routerLinkActive="active">
          {{item.title}}
        </a>
      </p>
    </div>
    <div class="laptop" [class.item-header]="item.comments_count > 0 || item.type === 'job'" [class.head-margin]="item.text">
      <p *ngIf="hasUrl">
        <a class="title" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
        {{item.title}}
        </a>
        <span *ngIf="item.domain" class="domain">({{item.domain}})</span>
      </p>
      <p *ngIf="!hasUrl">
        <a class="title" [routerLink]="['/item', item.id]" routerLinkActive="active">
        {{item.title}}
        </a>
      </p>
      <div class="subtext">
        <span *ngIf="item.type !== 'job'">
        {{item.points}} points by
          <a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a>
        </span>
        <span [class.item-details]="item.type !== 'job'">
          {{item.time_ago}}
          <span *ngIf="item.type !== 'job'"> |
            <a [routerLink]="['/item', item.id]" routerLinkActive="active">
             {{item.comments_count | comment }}
            </a>
          </span>
        </span>
      </div>
    </div>
    <div *ngIf="item.type === 'poll'" class="pollResults">
      <div *ngFor="let pollResult of item.poll" class="pollContent">
        <div [innerHTML]="pollResult.content | safeHtml"></div>
        <div class="subtext">{{pollResult.points}} points</div>
        <div class="pollBar" [ngStyle]="{'width': pollResult.points/item.poll_votes_count*100+'%'}"></div>
      </div>
    </div>
    <p class="subject" [innerHTML]="item.content | safeHtml"></p>
    <ul class="comment-list">
      <li *ngFor="let comment of item.comments" >
        <app-comment [comment]="comment"></app-comment>
      </li>
    </ul>
  </div>
</div>
