// react-app/src/components/ItemDetails/ItemDetails.tsx
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';

import { fetchItemContent } from '../../api/hackerNews';
import { useSettings } from '../../context/SettingsContext';
import type { Story } from '../../models/story';
import { Comment } from '../Comment/Comment';
import { ErrorMessage } from '../ErrorMessage/ErrorMessage';
import { Loader } from '../Loader/Loader';
import { formatCommentCount } from '../../utils/formatCommentCount';
import { sanitizeHtml } from '../../utils/sanitizeHtml';

import './ItemDetails.scss';

export default function ItemDetails() {
    const params = useParams();
    const navigate = useNavigate();
    const { settings } = useSettings();
    const itemID = Number(params.id);

    const [item, setItem] = useState<Story | undefined>(undefined);
    const [errorMessage, setErrorMessage] = useState('');

    useEffect(() => {
        const controller = new AbortController();

        fetchItemContent(itemID, controller.signal)
            .then((fetchedItem) => setItem(fetchedItem))
            .catch((error: unknown) => {
                if (error instanceof DOMException && error.name === 'AbortError') {
                    return;
                }
                setErrorMessage('Could not load item comments.');
            });

        window.scrollTo(0, 0);

        return () => controller.abort();
    }, [itemID]);

    const hasUrl = (item?.url ?? '').indexOf('http') === 0;
    const target = settings.openLinkInNewTab ? '_blank' : undefined;
    const rel = settings.openLinkInNewTab ? 'noopener' : undefined;

    const laptopClasses = ['laptop'];
    if (item && (item.comments_count > 0 || item.type === 'job')) {
        laptopClasses.push('item-header');
    }
    if (item && item.text) {
        laptopClasses.push('head-margin');
    }

    return (
        <div className="c-item-details">
            <div className="main-content">
                {!item && !errorMessage ? <Loader /> : null}
                {!item && errorMessage !== '' ? <ErrorMessage message={errorMessage} /> : null}

                {item ? (
                    <div className="item">
                        <div className="mobile item-header">
                            <p className="title-block">
                                <span className="back-button" onClick={() => navigate(-1)}></span>
                                {hasUrl ? (
                                    <a className="title" href={item.url} target={target} rel={rel}>
                                        {` ${item.title} `}
                                    </a>
                                ) : (
                                    <Link className="title" to={`/item/${item.id}`}>
                                        {` ${item.title} `}
                                    </Link>
                                )}
                            </p>
                        </div>
                        <div className={laptopClasses.join(' ')}>
                            {hasUrl ? (
                                <p>
                                    <a className="title" href={item.url} target={target} rel={rel}>
                                        {` ${item.title} `}
                                    </a>
                                    {item.domain ? <span className="domain">{`(${item.domain})`}</span> : null}
                                </p>
                            ) : (
                                <p>
                                    <Link className="title" to={`/item/${item.id}`}>
                                        {` ${item.title} `}
                                    </Link>
                                </p>
                            )}
                            <div className="subtext">
                                {item.type !== 'job' ? (
                                    <span>
                                        {` ${item.points} points by `}
                                        <Link to={`/user/${item.user}`}>{item.user}</Link>
                                    </span>
                                ) : null}
                                <span className={item.type !== 'job' ? 'item-details' : undefined}>
                                    {` ${item.time_ago} `}
                                    {item.type !== 'job' ? (
                                        <span>
                                            {' | '}
                                            <Link to={`/item/${item.id}`}>
                                                {` ${formatCommentCount(item.comments_count)} `}
                                            </Link>
                                        </span>
                                    ) : null}
                                </span>
                            </div>
                        </div>
                        {item.type === 'poll' ? (
                            <div className="pollResults">
                                {(item.poll ?? []).map((pollResult, index) => (
                                    <div className="pollContent" key={index}>
                                        <div dangerouslySetInnerHTML={{ __html: sanitizeHtml(pollResult.content) }}></div>
                                        <div className="subtext">{`${pollResult.points} points`}</div>
                                        <div
                                            className="pollBar"
                                            style={{
                                                width: `${(pollResult.points / item.poll_votes_count) * 100}%`,
                                            }}
                                        ></div>
                                    </div>
                                ))}
                            </div>
                        ) : null}
                        <p className="subject" dangerouslySetInnerHTML={{ __html: sanitizeHtml(item.content ?? '') }}></p>
                        <ul className="comment-list">
                            {(item.comments ?? []).map((comment) => (
                                <li key={comment.id}>
                                    <Comment comment={comment} />
                                </li>
                            ))}
                        </ul>
                    </div>
                ) : null}
            </div>
        </div>
    );
}

// src/app/item-details/item-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs/Subscription';

import { HackerNewsAPIService } from '../shared/services/hackernews-api.service';
import { SettingsService } from '../shared/services/settings.service';

import { Story } from '../shared/models/story';
import { Settings } from '../shared/models/settings';

@Component({
  selector: 'app-item-details',
  templateUrl: './item-details.component.html',
  styleUrls: ['./item-details.component.scss']
})
export class ItemDetailsComponent implements OnInit {
  sub: Subscription;
  item: Story;
  errorMessage = '';
  settings: Settings;

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private _settingsService: SettingsService,
    private route: ActivatedRoute,
    private _location: Location
  ) {
    this.settings = this._settingsService.settings;
  }

  ngOnInit() {
    this.sub = this.route.params.subscribe(params => {
      const itemID = +params.id;
      this._hackerNewsAPIService.fetchItemContent(itemID).subscribe(item => {
        this.item = item;
      }, error => this.errorMessage = 'Could not load item comments.');
    });
    window.scrollTo(0, 0);
  }

  goBack() {
    this._location.back();
  }

  get hasUrl(): boolean {
    return this.item.url.indexOf('http') === 0;
  }

}

<div class="main-content">
  <app-loader *ngIf="!item && !errorMessage"></app-loader>
  <app-error-message [message]="errorMessage" *ngIf="!item && errorMessage !== ''"></app-error-message>

  <div *ngIf="item" class="item">
    <div class="mobile item-header">
      <p class="title-block">
        <span class="back-button" (click)="goBack()"></span>
        <a *ngIf="hasUrl" class="title" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
          {{item.title}}
        </a>
        <a *ngIf="!hasUrl" class="title" [routerLink]="['/item', item.id]"
          routerLinkActive="active">
          {{item.title}}
        </a>
      </p>
    </div>
    <div class="laptop" [class.item-header]="item.comments_count > 0 || item.type === 'job'" [class.head-margin]="item.text">
      <p *ngIf="hasUrl">
        <a class="title" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
        {{item.title}}
        </a>
        <span *ngIf="item.domain" class="domain">({{item.domain}})</span>
      </p>
      <p *ngIf="!hasUrl">
        <a class="title" [routerLink]="['/item', item.id]" routerLinkActive="active">
        {{item.title}}
        </a>
      </p>
      <div class="subtext">
        <span *ngIf="item.type !== 'job'">
        {{item.points}} points by
          <a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a>
        </span>
        <span [class.item-details]="item.type !== 'job'">
          {{item.time_ago}}
          <span *ngIf="item.type !== 'job'"> |
            <a [routerLink]="['/item', item.id]" routerLinkActive="active">
             {{item.comments_count | comment }}
            </a>
          </span>
        </span>
      </div>
    </div>
    <div *ngIf="item.type === 'poll'" class="pollResults">
      <div *ngFor="let pollResult of item.poll" class="pollContent">
        <div [innerHTML]="pollResult.content | safeHtml"></div>
        <div class="subtext">{{pollResult.points}} points</div>
        <div class="pollBar" [ngStyle]="{'width': pollResult.points/item.poll_votes_count*100+'%'}"></div>
      </div>
    </div>
    <p class="subject" [innerHTML]="item.content | safeHtml"></p>
    <ul class="comment-list">
      <li *ngFor="let comment of item.comments" >
        <app-comment [comment]="comment"></app-comment>
      </li>
    </ul>
  </div>
</div>
