// react-app/src/feeds/item/ItemComponent.tsx
import type { Story } from '../../shared/models/story';
import { commentLabel } from '../../shared/pipes/comment';
import { RouterLink } from '../../shared/router/RouterLink';
import { scope, type Scope } from '../../shared/scope';
import { useSettings } from '../../shared/services/use-settings';
import './item.component.scss';

const ng = scope('item');

interface ItemComponentProps {
    item: Story;
    /** Attributes the parent template puts on this component's host element. */
    host: Scope & { className?: string };
}

export function ItemComponent({ item, host }: ItemComponentProps) {
    const settings = useSettings();
    const hasUrl = item.url.indexOf('http') === 0;
    const target = settings.openLinkInNewTab ? '_blank' : undefined;
    const rel = settings.openLinkInNewTab ? 'noopener' : undefined;

    return (
        <item {...host}>
            <div {...ng} style={{ marginBottom: `${settings.listSpacing}px` }}>
                {hasUrl ? (
                    <p {...ng}>
                        <a
                            {...ng}
                            className="title"
                            style={{ fontSize: `${settings.titleFontSize}px` }}
                            href={item.url}
                            target={target}
                            rel={rel}
                        >
                            {` ${item.title} `}
                        </a>
                        {item.domain ? (
                            <span {...ng} className="domain">
                                {`(${item.domain})`}
                            </span>
                        ) : null}
                    </p>
                ) : (
                    <p {...ng}>
                        <RouterLink
                            ng={ng}
                            className="title"
                            style={{ fontSize: `${settings.titleFontSize}px` }}
                            to={`/item/${item.id}`}
                        >
                            {` ${item.title} `}
                        </RouterLink>
                    </p>
                )}
                <div {...ng} className="subtext-palm">
                    {item.type !== 'job' ? (
                        <div {...ng} className="details">
                            <span {...ng} className="name">
                                <RouterLink ng={ng} to={`/user/${item.user}`}>
                                    {item.user}
                                </RouterLink>
                            </span>
                            <span {...ng} className="right">
                                {`${item.points} \u2605`}
                            </span>
                        </div>
                    ) : null}
                    <div {...ng} className="details">
                        {` ${item.time_ago} `}
                        {item.type !== 'job' ? (
                            <RouterLink ng={ng} to={`/item/${item.id}`} className="comment-number">
                                {` \u2022 ${commentLabel(item.comments_count)} `}
                            </RouterLink>
                        ) : null}
                    </div>
                </div>
                <div {...ng} className="subtext-laptop">
                    {item.type !== 'job' ? (
                        <span {...ng}>
                            {` ${item.points} points by `}
                            <RouterLink ng={ng} to={`/user/${item.user}`}>
                                {item.user}
                            </RouterLink>
                        </span>
                    ) : null}
                    <span {...ng} className={item.type !== 'job' ? 'item-details' : undefined}>
                        {` ${item.time_ago} `}
                        {item.type !== 'job' ? (
                            <span {...ng}>
                                {' | '}
                                <RouterLink ng={ng} to={`/item/${item.id}`}>
                                    {` ${commentLabel(item.comments_count)} `}
                                </RouterLink>
                            </span>
                        ) : null}
                    </span>
                </div>
            </div>
        </item>
    );
}

// src/app/feeds/item/item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Story } from '../../shared/models/story';

import { SettingsService } from '../../shared/services/settings.service';
import { BookmarkService } from '../../shared/services/bookmark.service';
import { Settings } from '../../shared/models/settings';

@Component({
  selector: 'item',
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.scss']
})
export class ItemComponent implements OnInit {
  @Input() item: Story;
  settings: Settings;
  isBookmarked: boolean;

  constructor(
    private _settingsService: SettingsService,
    private _bookmarkService: BookmarkService
  ) {
    this.settings = this._settingsService.settings;
  }

  ngOnInit() {
    this.isBookmarked = this._bookmarkService.isBookmarked(this.item.id);
  }

  toggleBookmark(): void {
    this.isBookmarked = this._bookmarkService.toggleBookmark(this.item);
  }

  get hasUrl(): boolean {
    return this.item.url.indexOf('http') === 0;
  }
}

<div [ngStyle]="{'margin-bottom': settings.listSpacing+'px'}">
  <p *ngIf="hasUrl">
    <a class="title" [ngStyle]="{'font-size': settings.titleFontSize+'px'}" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
      {{item.title}}
    </a>
    <span *ngIf="item.domain" class="domain">({{item.domain}})</span>
  </p>
  <p *ngIf="!hasUrl">
    <a class="title" [ngStyle]="{'font-size': settings.titleFontSize+'px'}" [routerLink]="['/item', item.id]" routerLinkActive="active">
      {{item.title}}
    </a>
  </p>
  <div class="subtext-palm">
    <div class="details" *ngIf="item.type !== 'job'">
      <span class="name"><a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a></span>
      <span class="right">
        {{item.points}} ★
        <span class="bookmark-icon" (click)="toggleBookmark()" [class.bookmarked]="isBookmarked" title="{{isBookmarked ? 'Remove bookmark' : 'Save story'}}">
          &#9733;
        </span>
      </span>
    </div>
    <div class="details">
    {{ item.time_ago }}
    <a [routerLink]="['/item', item.id]" routerLinkActive="active" class="comment-number" *ngIf="item.type !== 'job'"> •
      {{item.comments_count | comment }}
    </a>
    </div>
  </div>
  <div class="subtext-laptop">
    <span *ngIf="item.type !== 'job'">
      {{item.points}} points by
      <a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a>
    </span>
    <span [class.item-details]="item.type !== 'job'">
      {{ item.time_ago }}
      <span *ngIf="item.type !== 'job'"> |
        <a [routerLink]="['/item', item.id]" routerLinkActive="active">
          {{item.comments_count | comment }}
        </a>
      </span>
    </span>
    <span class="bookmark-icon" (click)="toggleBookmark()" [class.bookmarked]="isBookmarked" title="{{isBookmarked ? 'Remove bookmark' : 'Save story'}}">
      &#9733;
    </span>
  </div>
</div>
