// web-react/src/components/Settings.tsx
import { useSettingsStore } from '../stores/settings';
import './Settings.scss';

export function Settings() {
  const openLinkInNewTab = useSettingsStore((s) => s.openLinkInNewTab);
  const theme = useSettingsStore((s) => s.theme);
  const titleFontSize = useSettingsStore((s) => s.titleFontSize);
  const listSpacing = useSettingsStore((s) => s.listSpacing);
  const toggleSettings = useSettingsStore((s) => s.toggleSettings);
  const toggleOpenLinksInNewTab = useSettingsStore((s) => s.toggleOpenLinksInNewTab);
  const setTheme = useSettingsStore((s) => s.setTheme);
  const setFont = useSettingsStore((s) => s.setFont);
  const setSpacing = useSettingsStore((s) => s.setSpacing);

  return (
    <div id="popup1" className="overlay">
      <div className="popup">
        <h1>Settings</h1>
        <hr />
        <span className="close" onClick={toggleSettings}>
          &times;
        </span>
        <div className="content">
          <div className="control-section">
            <h2>Links</h2>
            <input
              type="checkbox"
              checked={openLinkInNewTab}
              onChange={toggleOpenLinksInNewTab}
            />
            Open links in a new tab
          </div>
          <div className="theme-controls">
            <div className="control-section">
              <h2>Select a theme</h2>
              <div>
                <label>
                  <input
                    name="theme"
                    type="radio"
                    value="default"
                    checked={theme === 'default'}
                    onChange={() => setTheme('default')}
                    onClick={() => setTheme('default')}
                  />
                  Default
                </label>
              </div>
              <div>
                <label>
                  <input
                    name="theme"
                    type="radio"
                    value="night"
                    checked={theme === 'night'}
                    onChange={() => setTheme('night')}
                    onClick={() => setTheme('night')}
                  />
                  Night
                </label>
              </div>
              <div>
                <label>
                  <input
                    name="theme"
                    type="radio"
                    value="amoledblack"
                    checked={theme === 'amoledblack'}
                    onChange={() => setTheme('amoledblack')}
                    onClick={() => setTheme('amoledblack')}
                  />
                  Black (AMOLED)
                </label>
              </div>
            </div>
            <div className="control-section">
              <h2>Change Font</h2>
              <div>
                <label>
                  Font size:
                  <input
                    min="1"
                    value={titleFontSize}
                    name="theme"
                    type="number"
                    onChange={(e) => setFont(e.target.value)}
                    onKeyUp={(e) => setFont((e.target as HTMLInputElement).value)}
                  />
                </label>
              </div>
              <div>
                <label>
                  List spacing:
                  <input
                    min="0"
                    value={listSpacing}
                    name="theme"
                    type="number"
                    onChange={(e) => setSpacing(e.target.value)}
                    onKeyUp={(e) => setSpacing((e.target as HTMLInputElement).value)}
                  />
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/app/core/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';

import { SettingsService } from '../../shared/services/settings.service';
import { Settings } from '../../shared/models/settings';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss']
})
export class SettingsComponent implements OnInit {
  settings: Settings;

  constructor(private _settingsService: SettingsService) {
    this.settings = this._settingsService.settings;
  }

  ngOnInit() {
  }

  closeSettings() {
    this._settingsService.toggleSettings();
  }

  toggleOpenLinksInNewTab() {
    this._settingsService.toggleOpenLinksInNewTab();
  }

  selectTheme(theme) {
    this._settingsService.setTheme(theme);
  }

  selectAuto() {
    this._settingsService.enableAutoTheme();
  }

  changeTitleFont(val){
    this._settingsService.setFont(val);
  }

  changeSpacing(val){
    this._settingsService.setSpacing(val);
  }
}

<div id="popup1" class="overlay">
    <div class="popup">
        <h1>Settings</h1>
        <hr>
        <span class="close" (click)="closeSettings()">&times;</span>
        <div class="content">
            <div class="control-section">
                <h2>Links</h2>
                <input 
                    type="checkbox" 
                    [checked]="settings.openLinkInNewTab" 
                    (change)="toggleOpenLinksInNewTab()" />
                    Open links in a new tab
            </div>
            <div class="theme-controls">
                <div class="control-section">
                    <h2>Select a theme</h2>
                    <div>
                        <label>
                        <input #auto 
                            name="theme" 
                            type="radio" 
                            value="auto" 
                            [checked]="settings.autoTheme"
                            (click)="selectAuto()" />
                            Auto (follow system)
                        </label>
                    </div>
                    <div>
                        <label>
                        <input #default 
                            name="theme" 
                            type="radio" 
                            value="default" 
                            [checked]="!settings.autoTheme && settings.theme === default.value"
                            (click)="selectTheme(default.value)" />
                            Default
                        </label>
                    </div>
                    <div>
                        <label>
                        <input #night 
                            name="theme" 
                            type="radio" 
                            value="night" 
                            [checked]="!settings.autoTheme && settings.theme === night.value" 
                            (click)="selectTheme(night.value)" />
                            Night
                        </label>
                    </div>
                    <div>
                        <label>
                        <input 
                            #amoledblack 
                            name="theme" 
                            type="radio" 
                            value="amoledblack" 
                            [checked]="!settings.autoTheme && settings.theme === amoledblack.value"
                            (click)="selectTheme(amoledblack.value)" />
                            Black (AMOLED)
                        </label>
                    </div>
                </div>
                <div class="control-section">
                    <h2>Change Font</h2>
                    <div>
                        <label>
                        Font size:
                        <input 
                            #titleFont 
                            min="1" 
                            [value]="settings.titleFontSize" 
                            name="theme" 
                            type="number" 
                            (keyup)="changeTitleFont(titleFont.value)" />
                        </label>
                    </div>
                    <div>
                        <label>
                        List spacing:
                        <input 
                            #listSpacing 
                            min="0" 
                            [value]="settings.listSpacing" 
                            name="theme" 
                            type="number" 
                            (keyup)="changeSpacing(listSpacing.value)" />
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
